name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  ci:
    uses: czetsuyatech/nerv-actions/.github/workflows/ci.yml@main
    with:
      javaVersion: '25'
    secrets:
      githubToken: ${{ secrets.GH_PKG_TOKEN }}
      githubAppId: ${{ secrets.NERV_RELEASE_APP_ID }}
      githubAppPrivateKey: ${{ secrets.NERV_RELEASE_APP_PRIVATE_KEY }}
